import { randomUUID } from 'node:crypto';
import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { minorToProviderAmount, type PaymentStatus } from '@frntdesk/shared';
import type { Env } from '../../config/env.schema.js';
import type {
  CollectRequest,
  CollectResult,
  PaymentProviderAdapter,
  StatusResult,
} from './payment-provider.js';

/** MTN's `status` values, mapped onto ours. Anything unrecognized stays PENDING. */
const STATUS_MAP: Record<string, PaymentStatus> = {
  PENDING: 'PENDING',
  SUCCESSFUL: 'SUCCESSFUL',
  FAILED: 'FAILED',
  TIMEOUT: 'TIMEOUT',
};

interface TokenCache {
  token: string;
  expiresAt: number;
}

/**
 * MTN MoMo Collections.
 *
 * Two things here are easy to get wrong and are therefore explicit:
 *   * `X-Reference-Id` is generated by *us* and is the transaction's identity
 *     for every later status poll — it is stored as `providerRef` before the
 *     request is sent, so a request that times out mid-flight is still
 *     traceable rather than orphaned.
 *   * The sandbox only accepts EUR. `MTN_WIRE_CURRENCY` decides what goes on
 *     the wire while the database keeps recording ZMW; the env schema refuses
 *     to boot a production build with anything but ZMW.
 */
@Injectable()
export class MtnPaymentProvider implements PaymentProviderAdapter {
  readonly key = 'MTN_MOMO' as const;
  private readonly logger = new Logger(MtnPaymentProvider.name);
  private tokenCache: TokenCache | null = null;

  constructor(private readonly config: ConfigService<Env, true>) {}

  async collect(request: CollectRequest): Promise<CollectResult> {
    const referenceId = randomUUID();
    const token = await this.accessToken();
    const callbackUrl = this.config.get('MTN_CALLBACK_URL', { infer: true });

    const response = await fetch(`${this.baseUrl()}/collection/v1_0/requesttopay`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'X-Reference-Id': referenceId,
        'X-Target-Environment': this.config.get('MTN_TARGET_ENVIRONMENT', { infer: true }),
        'Ocp-Apim-Subscription-Key': this.subscriptionKey(),
        ...(callbackUrl ? { 'X-Callback-Url': callbackUrl } : {}),
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        amount: minorToProviderAmount(request.amountMinor),
        currency: request.wireCurrency,
        externalId: request.externalId,
        payer: { partyIdType: 'MSISDN', partyId: request.payer.msisdnDigits },
        payerMessage: request.description.slice(0, 160),
        payeeNote: request.description.slice(0, 160),
      }),
    });

    // 202 Accepted is the success case — the prompt is now on the handset.
    if (response.status !== 202) {
      const body = await safeText(response);
      this.logger.warn(`MTN requesttopay rejected (${response.status}): ${body}`);
      return {
        providerRef: referenceId,
        status: 'FAILED',
        failureReason: `The payment could not be started (${response.status}).`,
      };
    }

    return { providerRef: referenceId, status: 'PENDING' };
  }

  async status(providerRef: string): Promise<StatusResult> {
    const token = await this.accessToken();
    const response = await fetch(
      `${this.baseUrl()}/collection/v1_0/requesttopay/${providerRef}`,
      {
        headers: {
          Authorization: `Bearer ${token}`,
          'X-Target-Environment': this.config.get('MTN_TARGET_ENVIRONMENT', { infer: true }),
          'Ocp-Apim-Subscription-Key': this.subscriptionKey(),
        },
      },
    );

    if (!response.ok) {
      const body = await safeText(response);
      // An unreadable status is *not* a failed payment — leaving it PENDING
      // keeps the reconciliation worker polling rather than declaring a loss.
      this.logger.warn(`MTN status ${providerRef} unreadable (${response.status}): ${body}`);
      return { status: 'PENDING', raw: { httpStatus: response.status, body } };
    }

    const raw = (await response.json()) as { status?: string; reason?: string };
    const mapped = STATUS_MAP[raw.status ?? ''] ?? 'PENDING';
    return {
      status: mapped,
      ...(mapped === 'FAILED' || mapped === 'TIMEOUT'
        ? { failureReason: raw.reason ?? 'The payment did not go through.' }
        : {}),
      raw,
    };
  }

  /**
   * MoMo access tokens are short-lived. Cached with a minute of headroom so a
   * poll that starts just before expiry does not land with a dead token.
   */
  private async accessToken(): Promise<string> {
    if (this.tokenCache && this.tokenCache.expiresAt > Date.now() + 60_000) {
      return this.tokenCache.token;
    }

    const apiUser = this.config.get('MTN_API_USER', { infer: true });
    const apiKey = this.config.get('MTN_API_KEY', { infer: true });
    const basic = Buffer.from(`${apiUser}:${apiKey}`).toString('base64');

    const response = await fetch(`${this.baseUrl()}/collection/token/`, {
      method: 'POST',
      headers: {
        Authorization: `Basic ${basic}`,
        'Ocp-Apim-Subscription-Key': this.subscriptionKey(),
      },
    });

    if (!response.ok) {
      throw new Error(`MTN token request failed (${response.status}).`);
    }

    const body = (await response.json()) as { access_token: string; expires_in: number };
    this.tokenCache = {
      token: body.access_token,
      expiresAt: Date.now() + body.expires_in * 1000,
    };
    return body.access_token;
  }

  private baseUrl(): string {
    return (this.config.get('MTN_BASE_URL', { infer: true }) ?? '').replace(/\/$/, '');
  }

  private subscriptionKey(): string {
    return this.config.get('MTN_SUBSCRIPTION_KEY', { infer: true }) ?? '';
  }
}

async function safeText(response: Response): Promise<string> {
  try {
    return (await response.text()).slice(0, 500);
  } catch {
    return '<unreadable>';
  }
}
