import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Injectable, inject } from '@angular/core';
import type { Observable } from 'rxjs';
import {
  IDEMPOTENCY_HEADER,
  type CheckoutRequest,
  type CheckoutResponse,
  type Payment,
} from '@frntdesk/shared';

@Injectable({ providedIn: 'root' })
export class PaymentsApi {
  private readonly http = inject(HttpClient);

  /**
   * The idempotency key is generated by the caller and held across retries of
   * the *same* attempt, so a double-tapped button reuses it and the API
   * returns the original payment instead of prompting the handset twice.
   */
  checkout(body: CheckoutRequest, idempotencyKey: string): Observable<CheckoutResponse> {
    return this.http.post<CheckoutResponse>('/api/checkout', body, {
      headers: new HttpHeaders({ [IDEMPOTENCY_HEADER]: idempotencyKey }),
    });
  }

  status(paymentId: string): Observable<Payment> {
    return this.http.get<Payment>(`/api/payments/${paymentId}`);
  }
}
